### ISSUE TITLE
PDF Report and Print View

### ISSUE THREAD

**Issue by mark-chandler** [mitre/heimdall2#1161]
In the features for Heimdall-Lite, "PDF Report and Print View" is listed.
I've uploaded scan results in a JSON file. But, I haven't been able to find an option in the web-page to generate a PDF report, and I haven't found it in the documentation.
Where can I find this? I'm using v2.4.3 of the docker image.

**Comment by rbclark** [comment]
This was a feature of the original Heimdall lite 1.0 (https://github.com/mitre/heimdall-lite-1.0) which did not get ported into 2.0. It was left in the README as an oversight. This is a feature we have actively been looking to re-add however we have not finalized a method to do so yet.

**Comment by mark-chandler** [comment]
No worries. Thanks for letting me know.
I've run a docker container for Heimdall-Lite-1.0:latest and can't see the feature there either. Any hints on where I can go looking?

Also, there are a couple of minor mistakes in the 1.0 README.md. (packager.io; docker container image refers to latest, not 1.0). They're only minor - so, let me know if you'd like me to report them somewhere.

**Comment by rbclark** [comment]
I believe this is referencing the "Expand All"/"Collapse All" feature in the top right corner once you load a result which allows you to print a report with all of the information included (either to PDF or on paper).

![Screen Shot 2021-04-01 at 9 48 36 AM](https://user-images.githubusercontent.com/2308869/113303815-71333900-92cf-11eb-9d57-bfbaa059945e.png)

Heimdall lite 1.0 is considered EOL at this point, we simply cannot archive the repository since it would cause https://mitre.github.io/heimdall-lite-1.0/ to not work anymore.

**Comment by mark-chandler** [comment]
Okay, great. I'll give that a go and see what results we get.
