### ISSUE TITLE
[Database Results] Tag editing, filtering, searching

### ISSUE THREAD

**Issue by Bialogs** [mitre/heimdall2#200]
Frontend components for tag editing, filtering and searching. Depends #181

The page for loading results from the database is currently very simple, it just displays a list of results. It should include the ability for users to add tags to results, and filter the results by name or tag.

**Comment by ejaronne** [comment]
Will this also allow us to restrict access based on a tag or group?

**Comment by aaronlippold** [comment]
A group would be a tag I think

**Comment by Bialogs** [comment]
This issue is only about organizing, filtering, and displaying the results in the user interface. It is NOT about authorization.

**Comment by ejaronne** [comment]
Thanks for the clarification. Is the next progression in establishing finer-grained access control going to leverage certain types of these tags somehow? I think it is important to have something beyond just the current owner or world. Otherwise this is stuff as a single-team server. We need something that will allow multiple teams to use a single Heimdall server. i.e., owner, team(group), or world. Thanks!

**Comment by Bialogs** [comment]
That feature is being worked in [this](https://github.com/mitre/heimdall2/issues/334) issue.
