### ISSUE TITLE
Need to revisit sizing and spacing issue on mobile and tablet after MVP for Heimdall 

### ISSUE THREAD

**Issue by aaronlippold** [mitre/heimdall2#226]

**Comment by rbclark** [comment]
Overall most pages look pretty good at the moment on mobile, the biggest issue is the pinning of the control headers takes up most of the page on mobile since the header row is so tall.

![Screen Shot 2021-06-07 at 10 18 56 AM](https://user-images.githubusercontent.com/2308869/121033953-9f734000-c77a-11eb-95f3-e9e1d745fec5.png)
