### ISSUE TITLE
Evaluations Controller and Service Testing

### ISSUE THREAD

**Issue by Bialogs** [mitre/heimdall2#32]
- [x] Service Spec

- [x] Controller Spec

- [x] e2e Spec

**Comment by samperry7** [comment]
Service spec- remove/delete needs work, I think it's something about importing the values from the constants files but not 100% sure on that.


Controller Spec- findbyid and create are testing fine, just needs the delete testing done


e2e spec- still messy, I think a lot of things have to get cut out of it because they were relevant to the user test but not evaluations (or at least not until more work is done)

Everything is pushed up that I had locally saved
