### ISSUE TITLE
Define UI for Manual and Inherited Control Implementation Status

### ISSUE THREAD

**Issue by ejaronne** [mitre/heimdall2#398]
As a planner, developer, admin, or operator, be able to:
1. Select or name a NIST SP 800-53 control, see the baseline title and description of control
2. Identify whether it is inherited, hybrid, or allocated
3. Specify the specific implementation details and links to any relevant artifacts
4. Provide name of attester, and date of attestation
5. Specify frequency for re-attestation.
6. Display results as any other results data
7. Allow for export of HDF json

**Comment by aaronlippold** [comment]
Can you also add our example data and the email chain we already worked on here as well

**Comment by rbclark** [comment]
I believe we came to conclusion on that this would happen as part of a separate workflow and not a part of heimdall itself. The attestation plugin that @rx294 is working on and perhaps a standalone helper to generate the `attestations.yml` file if deemed necessary. This should probably be closed since it no longer accurately describes the agreed upon approach.
