### ISSUE TITLE
[BUG] Converting HDF to CKL leads to wrong severity value assignment

### ISSUE THREAD

**Issue by georgedias** [mitre/heimdall2#5842]
**Describe the bug**
Converting an HDF STIG scan where a Vulnerability ID is set to `Not Applicable` leads to the wrong `Severity` value being set

***Explanation***
Converting from HDF to ckl the `Severity` (aka CAT level) is currently based on Impact levels. Unfortunately this means that a Status: Not Applicable, by convention in our InSpec profiles sets the Impact to Zero, subsequently setting the `Severity` to `low` which sets Vulnerability ID Severity to a CAT III without any validation (most often it is the wrong value).
The process logic should be thus:
- Map HDF's tag.severity to CAT level.
- If tag.severity does not exist, use Impact

**To Reproduce**
1. [Use the Heimdall demo and inspect the scan `b184b50-rhel-8_hardened`, id 1650](https://heimdall-demo.mitre.org/results/1650)
2. Review the results data for Vul ID SV-230226 - note that the `Severity` is set to none 
3. Export the scan to a Checklist (ckl) - (EXPORT -> Export as Checklist)
4. Open the ckl on the DISA STIG Viewer (2.17)
5. Import the appropriate STIG - RedHat Enterprise Linux 8 Security Technical Implementation Guide ([download it from the DISA site](https://dl.dod.cyber.mil/wp-content/uploads/stigs/zip/scc-5.9_rhel8_oracle-linux8_x86_64_bundle.zip))
6. Import the generated ckl exported in step 3
7. Compare the Severity for the Vul ID SV-230226 between the STIG and exported ckl. The STIG CAT is II and the ckl is set to III

**Comment by kemley76** [comment]
I have made more changes regarding this issue. This includes:
- adding a severity tag upon importing a Checklist file
- using a control's severity tag to compute its severity rather than defaulting to use only the impact value
- compute the amount of "impact bubbles" in the results view with the impact rather than the severity
- be able to sort the controls by impact when clicking the impact column header
- be able to show falsy values in the details (like when there is impact of 0)

Done in previous commit, but not listed out
- use severity tag (if available) when exporting form HDF to CKL
