### ISSUE TITLE
[Question] Notification Features

### ISSUE THREAD

**Issue by kneehill** [mitre/heimdall2#6331]
_I tried sending this as a question to the email address listed on the README ([inspec@mitre.org](mailto:inspec@mitre.org)), but it was undeliverable._

We were wondering if there’s any sort of capability to have notifications sent via email to designated users or groups whenever a new scan is uploaded.  Unfortunately, I couldn’t find any information in any of the other repo issues or the API documentation that mentioned any capability like this, so, if something like this already exists, I apologize for the oversight and would really appreciate if anyone could point me to the relevant documentation or instructions.
 
Otherwise, any information on possible workarounds would be helpful as well.

**Comment by Amndeep7** [comment]
Hi @kneehill.  Thanks for putting in this request.  I've added it to our internal backlog.  

Unfortunately, Heimdall does not currently have this capability - PRs are welcome if you have the time to contribute.

As a workaround, usually the scans that Heimdall ingests are artifacts from CI/CD pipelines.  Maybe you could create an additional step in that/those pipelines to send your team a notification in some manner.

Please ping me directly if you still need assistance.

Also, since we do not do any tracking of the folks that use our tools, I would appreciate it if you could send me an email at [amann@mitre.org](mailto:amann@mitre.org) so that we can discuss your usecase of Heimdall and explore how else we might be able to assist or collaborate.

**Comment by kneehill** [comment]
We were considering adding an additional step in our pipelines to do this but wanted to confirm that something didn't already exist within Heimdall itself.  Not a big deal at all, thank you so much for taking the time to respond!
