### ISSUE TITLE
Add Enhanced Logging Support

### ISSUE THREAD

**Issue by camdenmoors** [mitre/heimdall2#965]
I believe it would be beneficial for admins to be able to keep track of users' actions, for example:

```[DateTime - User IP] <User> created <EvaluationName>
[DateTime - User IP] <User> added groups <Group1, Group2> to evaluation <EvaluationName>
[DateTime - User IP] <User (Admin)> deleted user <User>
[DateTime - User IP] <IP> attempted logon as <User>
[DateTime - User IP] <IP> attempted LDAP logon as <User>
```

This should be able to integrate with existing logging providers such as:

[Azure Monitor](https://azure.microsoft.com/en-us/services/monitor/)
[AWS Centralized Logging](https://aws.amazon.com/solutions/implementations/centralized-logging/)
[Google Cloud Logging](https://cloud.google.com/logging/)
[Logflare](https://logflare.app/)

Or just be as simple as logging to `/var/log/heimdall/server.log`.

**Comment by rbclark** [comment]
The issue with integrating with existing logging providers is it adds another thing that must be accessible by the Heimdall Server (which isn't realistic in many environments). Logging to the server.log would not be very useful since most administrators aren't looking at the server.log all the time. These are things that would probably need to be tracked in the database. With that said, I don't think we should consider this feature until we've heard feedback from the end users on what they actually need.
